#!/bin/bash

WINPART=/dev/sda3
LWPART=/dev/sda6
TARGET_DIR=/mnt

function help()
{
	cat << HELP_MSG

Usage: $(basename $0) <command>

Command:
 -mr			Mount Windows Partition ($WINPART) on $TARGET_DIR in read-only mode
 -mw			Mount Windows Partition ($WINPART) on $TARGET_DIR in read-write mode
 -mlwr                  Mount LW Partition ($LWPART) on $TARGET_DIR in read-only mode
 -mlww                  Mount LW Partition ($LWPART) on $TARGET_DIR in read-write mode
 -u			Umount mounted partitions
 --help, -h, help 	Display this help message

HELP_MSG
}

if [ "$1" == '--help' ] ||  [ "$1" == '-h' ] ||  [ "$1" == 'help' ]; then
	help;
	exit 0;
fi

if [ "$1" == '-mr' ]; then

	echo "Mounting Windows partition ($WINPART) on $TARGET_DIR in read-only mode";
	sudo mount -r $WINPART $TARGET_DIR

elif [ "$1" == '-mw' ]; then

	echo "Mounting Windows partition ($WINPART) on $TARGET_DIR in read-write mode";
	sudo mount $WINPART $TARGET_DIR

elif [ "$1" == '-mlwr' ]; then

	echo "Mounting LW partition ($LWPART) on $TARGET_DIR in read-only mode";
	sudo mount -r $LWPART $TARGET_DIR

elif [ "$1" == '-mlww' ]; then

	echo "Mounting LW partition ($LWPART) on $TARGET_DIR in read-write mode";
	sudo mount $LWPART $TARGET_DIR

elif  [ "$1" == '-u' ]; then
	
	echo "Unmounting mounted partitions";
	sudo umount -R $TARGET_DIR

else
	help;
	exit 0;
fi

